spring.application.name=app


## PARA WHATSAPP

## codigo de recuperacion de twillio 7AMSLST7ET6KQ7KHJ4NSWZFC

# TWILIO - WHATSAPP SANDBOX
twilio.account-sid=AC2c8db0b72b00f24a2607b9ce420b64f8
twilio.auth-token=1b298f97940f97ff548f39bf23a0b6b2
twilio.whatsapp.from=whatsapp:+14155238886
twilio.whatsapp.to=whatsapp:+5493764110463